// src/constants/siteOptions.js

export const DEVELOPER_TITLES = [
    "Full Stack Developer",
    "Web Developer",
    "Laravel Developer",
    "VueJS Developer",
    "Frontend Developer",
    "Backend Developer",
    "Software Developer",
    "Application Developer",
    "System Developer",
    "PHP Developer",
    "UI/UX-Focused Developer",
    "JavaScript Developer",
    "Database Developer",
    "API Developer",
    "Information Systems Developer",
];

export const SKILL_CATEGORIES = [
    {
        title: "Front-End Development",
        skills: [
            "HTML5",
            "CSS3",
            "Bootstrap",
            "VueJS",
            "Vuetify",
            "JavaScript",
            "Responsive Design",
            "SASS/SCSS",
            "Tailwind CSS",
            "Vue Router",
            "Pinia / Vuex",
            "Axios",
        ],
    },
    {
        title: "Back-End & Systems",
        skills: [
            "PHP",
            "Laravel",
            "MySQL",
            "GitHub Desktop",
            "RESTful APIs",
            "Composer",
            "Laravel Eloquent",
            "Postman",
            "XAMPP",
            "Git",
        ],
    },
    {
        title: "Design & Creative Tools",
        skills: [
            "Canva",
            "Photoshop",
            "Capcut",
            "Figma (Basic)",
            "Adobe Illustrator",
            "Adobe Premiere Pro",
            "UI/UX Design",
        ],
    },
    {
        title: "Soft Skills",
        skills: [
            "Communication",
            "Attention to Details",
            "Continuous Learning",
            "Collaboration",
            "Creativity",
            "Focus",
            "Problem Solving",
            "Time Management",
            "Adaptability",
            "Critical Thinking",
        ],
    },
];

export const PROJECT_MATERIALS = {
    frontend: [
        "Vue",
        "Vue Router",
        "Pinia",
        "Vuetify",
        "React",
        "Next.js",
        "JavaScript",
        "TypeScript",
        "HTML",
        "CSS",
        "Tailwind CSS",
        "Bootstrap",
        "Sass",
        "SCSS",
    ],
    backend: ["Laravel", "PHP", "Node.js", "Express.js", "REST API", "GraphQL"],
    database: ["MySQL", "PostgreSQL", "SQLite", "MongoDB", "Firebase", "SQL"],
    design: ["Figma", "Photoshop", "Illustrator", "Adobe XD", "Canva"],
    tools: [
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Postman",
        "npm",
        "Composer",
        "Vite",
        "Docker",
        "CapCut",
    ],
    testing: ["PHPUnit", "Jest", "Cypress", "Unit Testing", "API Testing"],
    deployment: [
        "AWS",
        "Google Cloud",
        "DigitalOcean",
        "Vercel",
        "Netlify",
        "cPanel",
        "Linux",
    ],
    other: [
        "SEO",
        "Web Accessibility",
        "Performance Optimization",
        "Progressive Web App",
        "Agile",
        "Scrum",
    ],
};

export const SOCIAL_ICONS = [
    { name: "GitHub", value: "i-ri-github-fill" },
    { name: "Twitter/X", value: "i-ri-twitter-x-fill" },
    { name: "LinkedIn", value: "i-ri-linkedin-fill" },
    { name: "Instagram", value: "i-ri-instagram-fill" },
    { name: "Facebook", value: "i-ri-facebook-fill" },
    { name: "YouTube", value: "i-ri-youtube-fill" },
    { name: "TikTok", value: "i-ri-tiktok-fill" },
    { name: "Discord", value: "i-ri-discord-fill" },
    { name: "Website", value: "i-ri-global-line" },
    { name: "Email", value: "i-ri-mail-line" },
];
